[project]
name = "experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nkr", email = "wuxing_tong@163.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "requests>=2.34.2",
]

[project.scripts]
experiment = "experiment:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
